package co.uniminuto.edu.pojos;
// Generated 17/04/2019 01:32:46 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Apuesta generated by hbm2java
 */
public class Apuesta  implements java.io.Serializable {


     private Integer idApuesta;
     private String apuesta;
     private Integer valor;
     private Date fecha;
     private Byte estado;
     private int usuarioIdusuario;
     private int partidoIdpartido;

    public Apuesta() {
    }

	
    public Apuesta(int usuarioIdusuario, int partidoIdpartido) {
        this.usuarioIdusuario = usuarioIdusuario;
        this.partidoIdpartido = partidoIdpartido;
    }
    public Apuesta(String apuesta, Integer valor, Date fecha, Byte estado, int usuarioIdusuario, int partidoIdpartido) {
       this.apuesta = apuesta;
       this.valor = valor;
       this.fecha = fecha;
       this.estado = estado;
       this.usuarioIdusuario = usuarioIdusuario;
       this.partidoIdpartido = partidoIdpartido;
    }
   
    public Integer getIdApuesta() {
        return this.idApuesta;
    }
    
    public void setIdApuesta(Integer idApuesta) {
        this.idApuesta = idApuesta;
    }
    public String getApuesta() {
        return this.apuesta;
    }
    
    public void setApuesta(String apuesta) {
        this.apuesta = apuesta;
    }
    public Integer getValor() {
        return this.valor;
    }
    
    public void setValor(Integer valor) {
        this.valor = valor;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public Byte getEstado() {
        return this.estado;
    }
    
    public void setEstado(Byte estado) {
        this.estado = estado;
    }
    public int getUsuarioIdusuario() {
        return this.usuarioIdusuario;
    }
    
    public void setUsuarioIdusuario(int usuarioIdusuario) {
        this.usuarioIdusuario = usuarioIdusuario;
    }
    public int getPartidoIdpartido() {
        return this.partidoIdpartido;
    }
    
    public void setPartidoIdpartido(int partidoIdpartido) {
        this.partidoIdpartido = partidoIdpartido;
    }




}


