package co.uniminuto.edu.pojos;
// Generated 17/04/2019 01:32:46 PM by Hibernate Tools 4.3.1



/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private int idusuario;
     private String password;
     private String nombre;
     private String apellido;
     private String telefono;
     private String correo;
     private Integer saldo;
     private Byte rol;

    public Usuario() {
    }

	
    public Usuario(int idusuario) {
        this.idusuario = idusuario;
    }
    public Usuario(int idusuario, String password, String nombre, String apellido, String telefono, String correo, Integer saldo, Byte rol) {
       this.idusuario = idusuario;
       this.password = password;
       this.nombre = nombre;
       this.apellido = apellido;
       this.telefono = telefono;
       this.correo = correo;
       this.saldo = saldo;
       this.rol = rol;
    }
   
    public int getIdusuario() {
        return this.idusuario;
    }
    
    public void setIdusuario(int idusuario) {
        this.idusuario = idusuario;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }
    public Integer getSaldo() {
        return this.saldo;
    }
    
    public void setSaldo(Integer saldo) {
        this.saldo = saldo;
    }
    public Byte getRol() {
        return this.rol;
    }
    
    public void setRol(Byte rol) {
        this.rol = rol;
    }




}


